=== ManuelLerchner/MolSim-WS23-24/input/simulation_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fps" type="xs:integer" minOccurs="0" />
                <xs:element name="video_length" type="xs:integer" minOccurs="0" />
                <xs:element name="delta_t" type="xs:decimal" minOccurs="0" />
                <xs:element name="end_time" type="xs:decimal" minOccurs="0" />
                <xs:choice>
                    <xs:element name="ds_container" type="xs:string"/>              <!--  ds == direct_sum  and  lc == linked cells  -->
                    <xs:element name="lc_container">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="domain_size" type="xs:double" />
                                <xs:element name="cutoff_radius" type="xs:double" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>

                <xs:element name="cuboid" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="position" type="DoubleVec3" />
                            <xs:element name="grid_dim" type="IntVec3" />
                            <xs:element name="grid_spacing" type="xs:decimal" />
                            <xs:element name="temperature" type="xs:decimal" />
                            <xs:element name="mass" type="xs:decimal" />
                            <xs:element name="velocity" type="DoubleVec3" />
                            <xs:element name="type" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sphere" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="radius" type="xs:integer" />
                            <xs:element name="center_position" type="DoubleVec3" />
                            <xs:element name="initial_velocity" type="DoubleVec3" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DoubleVec3">
        <xs:sequence>
            <xs:element name="x" type="xs:double" />
            <xs:element name="y" type="xs:double" />
            <xs:element name="z" type="xs:double" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="IntVec3">
        <xs:sequence>
            <xs:element name="dimx" type="xs:int" />
            <xs:element name="dimy" type="xs:int" />
            <xs:element name="dimz" type="xs:int" />
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== ManuelLerchner/MolSim-WS23-24/input/body_collision_assignment3.xml
<?xml version="1.0"?>
<!-- just a sanity check: body collision rewritten to xml -->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="simulation_schema.xsd">
    <fps>24</fps>
    <video_length>30</video_length>
    <delta_t>0.0005</delta_t>
    <end_time>20.0</end_time>

    <!-- missing parameters for 'domain_size' and 'cutoff_radius' -->
    <!-- enable selection between direct sum or linked cells container, (active or implicit) -->

    <cuboid>
        <position>
            <x>20.0</x>
            <y>20.0</y>
            <z>0.0</z>
        </position>
        <grid_dim>
            <dimx>100</dimx>
            <dimy>20</dimy>
            <dimz>1</dimz>
        </grid_dim>
        <grid_spacing>1.1225</grid_spacing>
        <temperature>0.1</temperature>          <!-- aka mean brownian motion -->
        <mass>1</mass>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <type>0</type>
    </cuboid>

    <cuboid>
        <position>
            <x>70.0</x>
            <y>60.0</y>
            <z>0.0</z>
        </position>
        <grid_dim>
            <dimx>20</dimx>
            <dimy>20</dimy>
            <dimz>1</dimz>
        </grid_dim>
        <grid_spacing>1.1225</grid_spacing>
        <temperature>0.1</temperature>          <!-- aka mean brownian motion -->
        <mass>1</mass>
        <velocity>
            <x>0.0</x>
            <y>-10.0</y>
            <z>0.0</z>
        </velocity>
        <type>1</type>
    </cuboid>

</configuration>

=== ManuelLerchner/MolSim-WS23-24/tests/data/test_collision.xml
<?xml version="1.0"?>
<!-- just a sanity check: body collision rewritten to xml -->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../input/simulation_schema.xsd">
    <fps>24</fps>
    <video_length>10</video_length>
    <delta_t>0.0014</delta_t>
    <end_time>100.0</end_time>

    <output_format>XYZ</output_format>
    <directsum_container></directsum_container>
    <cuboid>
        <position>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </position>
        <grid_dim>
            <dimx>10</dimx>
            <dimy>2</dimy>
            <dimz>4</dimz>
        </grid_dim>
        <grid_spacing>2</grid_spacing>
        <temperature>2.2</temperature>          <!-- aka mean brownian motion -->
        <mass>1</mass>
        <velocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </velocity>
        <type>0</type>
    </cuboid>

    <cuboid>
        <position>
            <x>100.0</x>
            <y>20.0</y>
            <z>20.0</z>
        </position>
        <grid_dim>
            <dimx>3</dimx>
            <dimy>3</dimy>
            <dimz>3</dimz>
        </grid_dim>
        <grid_spacing>5</grid_spacing>
        <temperature>1</temperature>          <!-- aka mean brownian motion -->
        <mass>1.5</mass>
        <velocity>
            <x>-10.0</x>
            <y>-10.0</y>
            <z>0.0</z>
        </velocity>
        <type>2</type>
    </cuboid>

    <cuboid>
        <position>
            <x>20.0</x>
            <y>100.0</y>
            <z>100.0</z>
        </position>
        <grid_dim>
            <dimx>1</dimx>
            <dimy>1</dimy>
            <dimz>1</dimz>
        </grid_dim>
        <grid_spacing>3</grid_spacing>
        <temperature>10</temperature>          <!-- aka mean brownian motion -->
        <mass>100</mass>
        <velocity>
            <x>15.0</x>
            <y>15.0</y>
            <z>15.0</z>
        </velocity>
        <type>10</type>
    </cuboid>

</configuration>
